server:
  servlet:
    # 设置 Servlet 的上下文路径，这里为空表示根路径
    context-path:
    session:
      cookie:
        # 设置 Session Cookie 的路径
        path: /
    mmultipart:
        # 设置单个文件上传文件的最大不超过10MB
        max-file-size: 10MB
      # 设置一次性上传文件的最大不超过50MB
        max-request-size: 50MB
  # 服务监听端口
  port: 9901
# 指定对应的yml配置文件.
spring:
  profiles:
    active: dev-loginser
