spring:
  application:
    name: login-service
  config:
    import: nacos:login-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        注册中心配置文件
      config:
        server-addr: localhost:8848
        file-extension: yml
