spring:
  application:
    name: login-service
  config:
    import: nacos:application-dev.yml
#    #  指定对应的yml配置文件.
#    profiles:
#      active: nacos:application-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        注册中心配置文件
      config:
        server-addr: localhost:8848
        file-extension: yml

