server:
  port: 9998
spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=origin,gateway # 添加名为origin的请求头，值为gateway
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes:  # 路由
        - id: login-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://login-service # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/login/** # 断言，路径相匹配进行路由
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456-
#config:
#  redisTimeout: 60
